# 11.3 HttpException

### 1.first_ot_404的异常抛出流程
我们来接着看Aborter类中的first_ot_404流程,在first_ot_404调用流程中，由于不满足\_\_call__的前两个判断条件，最终会抛出self.mapping，其在构造函数中进行了声明
```python
class Aborter(object):

    """
    When passed a dict of code -> exception items it can be used as
    callable that raises exceptions.  If the first argument to the
    callable is an integer it will be looked up in the mapping, if it's
    a WSGI application it will be raised in a proxy exception.

    The rest of the arguments are forwarded to the exception constructor.
    """

    def __init__(self, mapping=None, extra=None):
        if mapping is None:
            mapping = default_exceptions
        self.mapping = dict(mapping)
        if extra is not None:
            self.mapping.update(extra)

    def __call__(self, code, *args, **kwargs):
        if not args and not kwargs and not isinstance(code, integer_types):
            raise HTTPException(response=code)
        if code not in self.mapping:
            raise LookupError('no exception for %r' % code)
        raise self.mapping[code](*args, **kwargs)
```
self.mapping是一个dict，其封装了default_exceptions，下面来看一下default_exceptions的装载，在_find_exceptions中完成。他的作用是扫描当前模块下所有HTTPException的子类对象，并装载到default_exceptions
```python
default_exceptions = {}
__all__ = ['HTTPException']


def _find_exceptions():
    for name, obj in iteritems(globals()):
        try:
            is_http_exception = issubclass(obj, HTTPException)
        except TypeError:
            is_http_exception = False
        if not is_http_exception or obj.code is None:
            continue
        __all__.append(obj.__name__)
        old_obj = default_exceptions.get(obj.code, None)
        if old_obj is not None and issubclass(obj, old_obj):
            continue
        default_exceptions[obj.code] = obj
_find_exceptions()
del _find_exceptions
```

最终Aborter函数的\_\_call__方法拿着封装好的self.mapping（实质是default_exceptions）通过参数传来的code去匹配相应的异常，并进行抛出。


以下为first_ot_404的总执行流程
![image.png](https://upload-images.jianshu.io/upload_images/7220971-552b85c9460607f9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 2.抛出异常后到浏览器异常界面的显示流程

因为first_or_404（）后面传入Aborter的code为404，所以其对应抛出的异常就是
NotFound对象,而其中的description描述文本，就是异常页面的显示文本
```python
class NotFound(HTTPException):

    """*404* `Not Found`

    Raise if a resource does not exist and never existed.
    """
    code = 404
    description = (
        'The requested URL was not found on the server.  '
        'If you entered the URL manually please check your spelling and '
        'try again.'
    )
```